const Discord = require("discord.js");

    module.exports.run = async (bot, message, args) => {
        function random_fact(fact)
         {
    
         return fact[Math.floor(Math.random()*fact.length)];
       
         }
         const fact = [
 		"In WWI, British armed merchant cruiser RMS Carmania engaged and sank the German merchant cruiser SMS Cap Trafalgar. Ironically, the two ships had been disguised as each other.",
 		"Minecraft’s world is approximately the same size as Neptune.",
 		"Place the word 'only' anywhere on the sentence: She told him that she loved him.",
 		"The average Icelander loses their virginity at 15.7 years old.",
 		"After leading the pack through the 2.4 mile swim, 112 mile bike, and the first 21 miles of the 26.2 mile run, John Dunbar lost his lead in the first ever Ironman triathlon because his crew ran out of water to give him, and switched to beer. He became drunk, and started running into parked cars.",
 		"After 'Showgirls' flopped at the box office, MGM changed its marketing strategy to encourage ironic enjoyment of the film, which has resulted in over $100 million in DVD and video rental revenue.",
 		"In the late 1940’s, comic books were seen as a direct cause of juvenile crime. Children were forced to burn their comics in schoolyards and a Senate hearing was held which led to the Comics Code Authority and later the Canadian ban of all comic books.",
 		"Winston Churchill and Mahatma Gandhi were enemies. Churchill favored letting Gandhi die if he went on a hunger strike. During the Bengal famine of 1943, his response to urgent requests to divert food supplies to India was 'if food was so scarce why Gandhi hasn’t died yet'.",
 		"The deepest note mankind has ever detected is a B♭ that is 57 octaves below middle C. The sound is made by inflating plasma bubbles in the center of the Perseus Cluster.",
 		"Early humans used to run their prey to death. This method of hunting was called persistence hunting.",
 		"When Russell Brand and Katy Perry divorced, Russell was eligible to claim half of the $44 million she earned during their marriage, but he declined.",
 		"Between 1993-98, a majority of US Senators were trading stocks and beating the market by 12 percentage points a year on average. By comparison, corporate insiders beat the market by just 5 percent, and typical households underperformed by 1.4 percent.",
 		"After the first Hiroshima atomic bombing in Japan, one Hiroshima policeman went to Nagasaki to teach police about ducking after the atomic flash. As a result of this timely warning, not a single Nagasaki policeman died in Nagasaki’s atomic blast.",
 		"All the poop generated on the US Navy’s newest Gerald R. Ford-class aircraft carrier will be vaporized by plasma.",
 		"A Missouri Man purposely damaged a levee on the Mississippi River to delay his wife coming home so he could party. He flooded 14,000 acres and was later arrested and convicted of causing a catastrophe and sentenced to life in prison.",
 		"10% of people don’t like Cilantro because when they eat it, they taste soap.",
 		"The sex of most turtles is determined by the temperature of the incubation of the eggs. Small changes in temperature can cause dramatic changes in the sex ratio. If eggs are incubated below 28°C, all turtles will be male. Above 31°C, every egg gives rise to a female.",
 		"In 1984, a 1-year-old received a heart transplant from a baboon but ended up dying 21 days later due to rejection. When questioned with why a baboon and not a primate more closely related to humans, the surgeon said he didn’t believe in evolution.",
 		"The Smithsonian opened an experimental museum in a predominantly Black neighborhood of Washington D.C. Many were skeptical that the Smithsonian would help the area, others worried about vandalism. The museum was untouched in the 1968 riots that destroyed other parts of the community.",
 		"Foxes have a gland on the tip of their tails that has a number of different uses, one of them being creating volatile terpenes.",
 		"Some farmers in Bangladesh have switched to raising ducks instead of chickens because, during catastrophic floods, ducks float.",
 		"Bob Fletcher was a man who took care of the farms of three Japanese American families while they were interned during WWII. By keeping their farms running and paying their taxes and mortgages, he ensured the families didn’t lose everything. He was even shot at for supporting them.",
 		"California law allows employees to take two hours paid time off in the beginning or end of the workday to vote on election day.",
 		"When actor Raul Julia was terminally ill, he decided that his last performance would be as the villain in Street Fighter, as his children were fans of the game it was based on. The movie received terrible reviews, but Julia’s performance was critically acclaimed.",
 		"To punish tree thieves who cut down trees illegally, some cities spray trees with fox urine around Christmas time. It freezes on them and is odorless outdoors, but would stink up your whole house if brought indoors; the smell is 'eye-watering.'",
 		"Ludger Sylbaris was a man thrown into solitary confinement after a bar brawl, survived one of the biggest volcanic eruptions of the 20th century because his cell was bombproof and poorly ventilated. He became one of only three known survivors of the event, and his prison cell still stands today.",
 		"Only 10 Scouts earned the Invention merit badge, which required obtaining a patent for an invention. It was discontinued in 1915 and is the rarest badge.",
 		"Lucius Cincinnatus was a Roman statesman and military leader who was given absolute power to rule the empire when it was attacked. After his victory, he immediately resigned his post as Dictator and went back to farming. The city of Cincinnati is named in his honor.",
 		"'Semantic satiation' is a psychological phenomenon in which repetition causes a word or phrase to temporarily lose meaning for the listener, who then perceives the speech as repeated meaningless sounds.",
 		"Every high school student in Sweden aged 16-20 is entitled to 'study grant' of $139 USD monthly. The only requirement is to attend school.",
 		"Car makers employ sound engineers to give car doors that satisfying 'thunk' when closed.",
 		"Pete Best, the original drummer of the Beatles, moved to America shortly after Best’s firing from the Beatles and released an album titled 'Best of the Beatles' which confused record buyers and generated large sales numbers due to consumers believing that it was a compilation of Beatles songs.",
 		"The 'Thagomizer', the spiked tail on a stegosaurid dinosaur, didn’t have an official name till the cartoonist Gary Larson did a comic about it, named it, and the scientific community just accepted it and started using it too.",
 		"In 1867, a jar was found in Paris containing a human rib among other artifacts, and a label claiming that they belonged to Joan of Arc. Tests conducted in 2006 revealed that they came not from Joan of Arc, but an Egyptian mummy.",
 		"The National Trust implores us to stop urinating in a toilet, in order to save the water used in flushing, and instead wee onto compost heaps, which speeds up the chemical process of decomposition, making it a better fertilizer to grow vegetables and save even more energy in reducing food miles.",
 		"Charlie No-Face or the Green Man was an urban legend about a monster who walked along the side of a highway at night in Pennsylvania. In reality, he was a man named Raymond Robinson, and he went out at night so that his face, disfigured in a childhood accident, wouldn’t scare people.",
 		"Adding an additional 20 minutes of commuting per day has the same negative effect on job satisfaction as receiving a 19% pay cut.",
 		"In 1140, a German King captured a castle and ordered all the women of the castle to leave with whatever they could carry on their backs. Thinking quickly, the women carried their men on their backs. The King kept his word and let the men live.",
 		"Charles Schulz always disliked the title of Peanuts, which was given to his comic strip by the syndicate. In a 1987 interview, Schulz said of it: 'It’s totally ridiculous, has no meaning, is simply confusing, and has no dignity and I think my humor has dignity.'",
 		"Michael Jordan took home economics in high school to learn to cook because he was worried his big ears would make it hard to find a woman who would want to marry him.",
 		"Within hours of its release in 1993, the video game DOOM was banned from numerous university networks as a rush of players overwhelmed their systems with deathmatches.",
 		"The Code of Hammurabi (1754 BC) has 282 laws inscribed on stone. It includes the concept of 'eye for an eye' and 'tooth for a tooth' more than 500 years before the Torah.",
 		"George Clooney had a cameo on South Park in which he provided all the barks, growls, and yips for Sparky, the gay dog in the 'Big Gay Al’s Big Gay Boat Ride.'",
 		"Crows in urban Japan and the United States have innovated a technique to crack hard-shelled nuts by dropping them onto crosswalks and letting them be run over and cracked by cars. Then they retrieve the cracked nuts when the cars are stopped at the red light.",
 		"3 cameras were standard in multi-cam tv filming prior to the 70s, then Garry Marshall needed the 4th camera to solely follow Robin Williams during Mork & Mindy filming since Williams was so unpredictable with his physical comedy.",
 		"The movie 'Paranormal Activity' had a budget of only $15,000 but made $194 million. During the screening, people were walking out that one studio executive thought the film was bombing. They later learned that the viewers were actually leaving because they were too frightened.",
 		"There is a monument in Georgia which gives instructions in 8 languages on how to rebuild society after an unknown apocalyptic event, whilst also functioning as a compass, calendar, and clock.",
 		"Calvin Klein’s cologne 'Obsession' can draw big cats like Tigers, Jaguars etc from as far as half a mile, who then proceed to take long sniffs and cuddling against the source, savouring the smell much longer than they savour even their meals.",
 		"Lynlee is the baby that was born twice. Pediatric surgeons, removed her from the womb to cut out a tumor on her spine, placed her back and several weeks later Lynlee was born healthy.",
 		"In 1897, 3 Swedes attempted to be the first people to reach the North Pole. They traveled by hot air balloon but crashed after 65 hours. 33 years later, a ship discovered their camp, along with their dead bodies, journal, and camera. They’d survived for weeks by killing and eating polar bears.",
 		"L. Ron. Hubbard’s own son, L. Ron Hubbard Jr. was highly critical of Scientology and claimed black magic was the inner core of Scientology once stating, 'my father did not worship Satan. He thought he was Satan.'",
 		"The Old Testament says farmers should leave the edges of their fields unharvested for the poor and traveling foreigners to eat.",
 		"After South Park aired the episode Chef Aid, the term 'Chewbacca Defense' entered the legal lexicon. The legal strategy aims to deliberately confuse juries than refute cases. The practice was widely used by lawyers before the episode, but South Park gave it a term.",
 		"'Steve Jobs' is the name of an Italian clothing company created in 2012 when the creators realized that Apple never trademarked Jobs’ name.",
 		"After Jean-Claude Van Damme’s biggest movie hit (Timecop 1994), he was offered a 3 picture deal at $12M per picture. He turned it down and demanded he gets the same deal as Jim Carrey $20M per movie. He was rejected and his career never recovered. He later admitted he 'acted like an idiot.'",
 		"The Rock travels with a private gym of over 40,000 lbs. of equipment that over 100 crew members assemble at each film location.",
 		"Devin Gaines earned 5 bachelor degrees with honors simultaneously at the University of Connecticut, averaging 24 credits a semester and 3 hours of sleep a night. He drowned in 2007 because he didn’t know how to swim.",
 		"The term and concept of 'jay-walking' was introduced in the 1920’s by the auto industry as part of a propaganda campaign to claim the roads for cars and shift the blame in accidents from cars to pedestrians. At the time 'Jay' was a slur with a similar meaning to 'redneck' or 'hillbilly.'",
 		"The human genome is 3.3Gb in size. HIV virus is only 9.7kb. Largest known virus genome is 2.47Mb (pandoravirus salinus). The largest known vertebrate genome is 130Gb (marbled lungfish). Largest known plant genome is 150Gb (Paris japonica). The largest known genome is 670Gb (Amoeboid) but is disputed.",
 		"At the request of President Truman, Coca-Cola made a special clear version of Coke for Soviet Marshal Georgy Zhukov, so he could pretend he was drinking vodka rather than an American drink.",
 		"Charlie Chaplin was criticized because he did not volunteer during the WWI. Although he registered for the U.S. draft, he received thousands of white feathers and angry letters. It was later revealed that he was rejected because he was undersized and underweight.",
 		"Most cities have poorer areas in the east, due to prevailing winds carrying smoke and odors that way during the industrial revolution.",
 		"At Jon Bon Jovi’s restaurant, JBJ Soul Kitchen, you can pay for your meal with either a donation or one hour of volunteer work in the kitchen. In 2014, JBJ served 11,500 meals, and half of them were paid for with a donation, and the other half was paid for with volunteer work.",
 		"Jimmy Carter has been alive for almost 38 years since leaving office. This is the longest post-presidential time in U.S. History.",
 		"Pink Floyd is inducted into the National Association of Brick Distributors’ Hall of Fame for their services to the brick industry through their 1979 album, 'The Wall'.",
 		"Sergeant Stubby, a stray dog found during military training in 1917, served with the 102nd Infantry Regiment in WWI, saving them repeatedly due to his ability to smell mustard gas at a distance. After the war, he became a celebrity, meeting three presidents and traveling around the country.",
 		"Before 9/11 there were only 16 people on the no-fly list. As of 2013, there are over 47,000 people now on the no-fly list.",
 		"In 2009, British PM Gordon Brown hand-wrote a letter of condolence to a mother whose son had died in Afghanistan, in which he misspelled the son’s surname. The Sun (a tabloid) wrote a scathing article criticizing his mistake. In this article, the paper misspelled the same name.",
 		"There was a bank robber dressed as Santa Claus who was responsible for the death of 6 people during his robbery and getaway. When he was caught and thrown in jail, nearly 2,000 people showed up, pushed past the guards, dragged him out of the jail and hanged him.",
 		"During the making of rush hour 2, the secret service confiscated $100m in prop money after filming due to it being so accurate that extras were able to spend it at local businesses.",
 		"Donnie Darko was filmed in 28 days which, coincidentally, virtually matches the time that transpired in the film. The movie took place between October 2nd, 1988 to the weekend party scene before Halloween on October 31st, 1988.",
 		"Harper Lee’s friends gave her a full year’s salary for Christmas in 1956 so that she’d be able to take a year off from work to write. Lee used that time to write 'To Kill a Mockingbird,' which has since sold over 30 million copies.",
 		"John Francis, an American environmentalist, decided to stop speaking for a day to learn to listen better to his opponents. He turned it into a 17-year vow of silence. During those 17 years, he went to school and even earned a Ph.D.",
 		"1-800-COLLECT was so popular in the 90s that AT&T launched a competing service, 1-800-Operator. However, AT&T later discovered many people misspell Operator with 'er' instead of 'or' at the end, and that unfortunately, 1-800-COLLECT owned the misspelled number and had been taking their customers.",
 		"Naked mole rats can survive 18 minutes without oxygen and suffer no lasting effects. They achieve this feat by switching their metabolism to use fructose, instead of glucose, something typically only done by plants.",
 		"A Medal of Honor recipient from WWII embarrassed a sitting U.S. senator (who was also a KKK member) by publicly praising the efforts of African-American veterans.",
 		"Arnold Schwarzenegger’s parents used to beat him because they thought he was gay since his bedroom walls were covered with posters of men instead of women.",
 		"Bill Darden (the founder of Red Lobster) opened his first restaurant, a luncheonette called The Green Frog in Wayward, Georgia at 19 in 1938. He refused to segregate customers by race. Segregation was a state law in 30’s Georgia.",
 		"Honeybees let out a 'whoop' when they bump into each other. This vibrational pulse, long thought to be a signal to other bees to stop what they are doing, might actually be an expression of surprise.",
 		"Elton John answered an ad for a talent search. After failing the audition he told the person behind the desk that he can’t write lyrics. He was handed an envelope with lyrics by another person who answered the ad and failed the audition Bernie Taupin, who then wrote the majority of Elton’s songs.",
 		"Joe DiMaggio was so devastated after Marilyn Monroe’s death that he had a half-dozen red roses delivered three times a week to her crypt for 20 years, never married again and his last words were: 'I’ll finally get to see Marilyn.'",
 		"Britain’s power stations have to learn television schedules to anticipate when there will be a huge power draw as everyone turns on their electric kettles during a break in a soap opera or sporting event. ",
 		"Japan has a sociological phenomena known as Hikikomori, in which there’s an estimated 1 million Japanese who choose to completely isolate themselves from society.",
 		"There is a specific order to Adjectives for the English language. Native speakers can just tell if it sounds right or not, and it may not be apparent to non-native speakers at first, in general, the order is: opinion, size, age/shape, color, origin, material, purpose.",
 		"The residents of a neighborhood complaining of mysterious ailments from a new cell phone tower. During a meeting, the owner revealed that the tower had been off for over a month. Residents didn’t show up to the follow-up meeting.",
 		"Ernest Thompson Seton, one of the founding pioneers of the Boy Scouts of America, was presented with an invoice for all the expenses connected with his childhood, by his father, including the fee charged by the doctor who delivered him. He paid the bill, but never spoke to his father again.",
 		"The code from the Matrix is actually a sushi recipe the production designer, Simon Whiteley, scanned from one of his wife’s Japanese cookbooks.",
 		"The power button symbol is based on binary’s off (0) and on (1).",
 		"After successfully winning the online poll to name the ISS module 'Colbert' after Stephen Colbert, NASA went with the eighth most popular name 'Tranquility'. To honor his winning, they named the new station treadmill Combined Operational Load Bearing External Resistance Treadmill (COLBERT).",
 		"Japanese Yakuza have a unique form of extortion known as sōkaiya. Instead of harassing small businesses for protection money, the yakuza harasses the stockholder meetings of large corporations.",
 		"Joey’s character in FRIENDS was not supposed to be dumb, according to the original script. It was only when Matt LeBlanc auditioned for Joey, he put a 'different spin' on the character, which was liked by the creators of the show.",
 		"Lebron James was so hated back in 2012 that even a captured Al-Qaeda member wrote letters expressing his disgust at his decision to go to the Miami Heat. He told his lawyer that 'LeBron James is a very bad man and should apologize to the city of Cleveland.'",
 		"Violent crime in New York City has been dropping since 1991 and as of 2017, is among the lowest of major cities in the United States. In 2017, there were 290 homicides, the lowest number since the 1940s.",
 		"A 12-year-old girl named Martina Maturana saved much of her village’s population from being killed by a tsunami when she noticed boats moving up and down in the morning and ran to ring the warning bell.",
 		"A small town in southern Kyoto, Japan has a yearly festival and monument next to a shrine dedicated to Thomas Edison. He used the bamboo from the town Yawata for his filament in the lightbulbs which increased the use time from 40 hours to 1,000.",
 		"After firefighters saved piglets from a barn fire, 6 months later the farmer sent them sausages made from the piglets as a thank you gift.",
 		"Infamous streaker, Mark Roberts, was sponsored by GoldenPalace.com to streak Super Bowl 38. He was paid $1 million, given front row tickets on the 50-yard line, and provided with one of the best defense attorneys in the U.S. who was able to reduce his charges down to a misdemeanor and $1,000 fine.",
 		"The CIA parachuted hundreds of people into North Korea throughout the 1950s to start resistance networks and, despite never hearing from most of them again, continued to parachute more in until an inquiry in the 1970s questioned the morality of such an initiative.",
 		"Firefighters in Pana, Ill found a cockroach infestation so massive that the city council agreed that the best option was to burn the house down.",
 		"When NASA was preparing for Sally Ride to travel as the first American female astronaut, engineers initially were at a loss about how many tampons to send. 'Is 100 the right number?' they asked her. 'No. That would not be the right number,' she replied.",
 		"Japanese researchers have created a fire-alarm for the deaf. It’s a gadget that emits a wasabi mist which will wake the endangered person and get them out of the building alive!"
 	];
 	  	message.channel.send(random_fact(fact));
 	 }  
    
    module.exports.help = {
    name: "fact" 
}